### ISSUE TITLE
Log a user in programmatically

### ISSUE THREAD

**Issue by ziguane** [gitblit/fathom#12]
Hello,

After a user creation in a Controller, how can I programmatically log the user in, to autorise the visit of a guarded (protected) page ?

**Comment by gitblit** [comment]
You have a couple choices: client-side session (cookie) or server-side session.  I do this with a [filter in Routes](https://github.com/gitblit/fathom/blob/master/fathom-integration-test/src/main/java/conf/Routes.java#L87-L105).

**Comment by ziguane** [comment]
I'am totally lost with this.


I'll try to be more specific. As you know I'am using Fathom 0.9.2 with the fathom-security module and a jdbc realm.
In my application, there is an html form to create account : fields are username, email and password.
This informations are sent to the method of a Controller, stored in a db and then I would like to log the user directly to the customer area ( avoid having to fill out the login form the first time )

// In my use case account will always be null 
Account account = ctx.getSession(AuthConstants.ACCOUNT_ATTRIBUTE);

if (account != null) {
      ctx.setLocal(AuthConstants.ACCOUNT_ATTRIBUTE, account);
}

It's not a mandatory feature, so I'll give up this idea, but I'am really curious to see how to do it in Fathom... really

Thanks

**Comment by gitblit** [comment]
I suggest you clone this repo and run the integration test app.  I'm not sure how you have it structured, but you can't do it completely with Controllers.  There are a few things we need to setup in `Routes`.  The Session check and Context setup must be implemented in a filter that you specify in `Routes`.  And the login/login controllers must be specified there too.

https://github.com/gitblit/fathom/tree/master/fathom-integration-test
https://github.com/gitblit/fathom/blob/master/fathom-integration-test/src/main/java/conf/Routes.java

**Comment by gitblit** [comment]
Ah. I just re-read your request.
Let me respond....

**Comment by gitblit** [comment]
In my own apps I haven't gotten to user registration yet but I have done some work with creating local user accounts who have successfully authenticated against an external system (e.g. LDAP, etc) and this is pretty similar.

I will assume you have successfully registered your user (username, password, permissions, etc, etc).  The plan is to inject the Fathom `SecurityManager`  into your controller, force an authentication of your newly created user, and then setup the local `Context` and `Session` with the returned account.  If you immediately redirect from this controller method then you don't have to bother setting up the local part of the `Context`.

To properly inject the `SecurityManager` you may have to play with the import statements depending on your IDE because there is a `java.lang.SecurityManager` too which IntelliJ prefers.  You'll need to import `fathom.security.SecurityManager`.

Something like this...


```java
@Path("/users")
public class MyController extends Controller {

    @Inject
    SecurityManager securityManager;

    @POST("/register")
    public void registerUser(String username, String password) {
        // do your really amazing user creation here

        // force an authentication of the newly created user & setup at least the session
        Account account = securityManager.authenticate(new StandardCredentials(username, password));
        getContext().setSession(AuthConstants.ACCOUNT_ATTRIBUTE, account);
        getContext().setLocal(AuthConstants.ACCOUNT_ATTRIBUTE, account);

        // then redirect to your secure page
        getContext().redirect("/secure/page");
    }
}
```

**Comment by ziguane** [comment]
It works very well... except in my case because of a @Transactional annotation on the method, but that not about Fathom

I was pretty near the solution, I just missed getContext().setSession(AuthConstants.ACCOUNT_ATTRIBUTE, account);

Thank for all

**Comment by gitblit** [comment]
Super.  Glad to hear that.
