### ISSUE TITLE
ORM Module

### ISSUE THREAD

**Issue by decebals** [gitblit/fathom#4]
Do you have a plan to add support for a ORM (JDBC, JPA, ...)?

**Comment by gitblit** [comment]
Not at the moment. I prefer to write my own persistence layer either based
on iciql or jdbi or Mongo without being limited to one DB which often seems
the case with the ORM integrations I've seen.

**Comment by decebals** [comment]
> without being limited to one DB which often seems the case with the ORM integrations I've seen

I don't understand this affirmation.

I will try `iciql` in a small project, I don't like `jdbi`.

**Comment by gitblit** [comment]
I guess that depends on what type of integration you were thinking of.  My assumption was you were thinking of `@Transaction`-ish annotated methods that automagically persist an object into a DB.  At the moment I haven't found that feature particularly useful.

My routes/controllers are thin.  They don't have a ton of logic.  Instead they hand-off received objects to one or more DAO instances.  The DAO instances have ORM references and perform all logic, insertion, and queries.  Because that is how I have been writing my apps I haven't seen the value in a Fathom ORM module.

Can you describe what ORM integration means to you?  Perhaps I should reconsider.
