### ISSUE TITLE
 Broken accents in submitted String 

### ISSUE THREAD

**Issue by ziguane** [gitblit/fathom#9]
Hi all,

In my fathom (0.8.4) project, accents in String submitted by forms (POST) are "broken"
   ex: retrieve "mÃ©tier" instead of "métier".

I found the following workaround but it's absolutely not a solution

String name = getRequest().getParameter("name").toString();
byte[] bytes = name.getBytes(StandardCharsets.ISO_8859_1);
name = new String(bytes, StandardCharsets.UTF_8);

Does someone else has already made this observation ?
Is there a place where I can globally force the charset to UTF-8 ?

I already asked a question about it on the Pippo mailing list...

**Comment by gitblit** [comment]
Neither Pippo nor Fathom are doing any transformations on the String.  I haven't run across this particular case before probably because any calls I make are encoded using the `%nn` syntax.

The underlying container is responsible for providing the String to Pippo/Fathom REST.  Digging into Undertow, I see that it supports a configurable `URL_CHARSET`.  Fathom does not directly configure a charset for decoding URLs so I would expect the default (UTF-8) to be used in `HttpRequestParser`.  Setting a breakpoint confirms UTF-8 is being used.

A unit test demonstrating the failure would be good.

**Comment by ziguane** [comment]
I solve the problem by setting a default encoding to "UTF-8" on the DeploymentInfo instance, in the fathom.Server class. The default value is "ISO-8859-1". ( https://github.com/undertow-io/undertow/blob/master/servlet/src/main/java/io/undertow/servlet/api/DeploymentInfo.java )

DeploymentInfo info = Servlets.deployment();
info.setDeploymentName("Fathom");
info.setClassLoader(this.getClass().getClassLoader());		info.setContextPath(settings.getContextPath());
info.setIgnoreFlush(true);

// below the code that I added.
info.setDefaultEncoding("UTF-8");


The problem occured with String parameters in form.
OSX 10.10.5
Java 1.8.0_102

I'm not a specialist unit tests, how to help ?
I wrote a simple project with a servlet that shows the difference between String retrieved with and without putting a UTF-8 encoding by default.

**Comment by gitblit** [comment]
Great news.  I will make that change in Fathom or you could make a PR.

**Comment by ziguane** [comment]
I made a PR. Hope it does not break anything.

Thank you for your help

**Comment by gitblit** [comment]
Fixed by #10
